#lang sicp

; Draw the tree illustrating the process generated by the count-change procedure of 
; section 1.2.2 (./examples/money-change.rkt) in making change for 11 cents. What are the orders of 
; growth of the space and number of steps used by this process as the amount to be changed increases?

; part of evaluation with substitution
; (count-change 11 5)
; (+ (count-change 11 4) (count-change -39 5))
; (+ (+ (count-change 11 3) (count-change -14 4)) 0)
; (+ (+ (+ (count-change 11 2) (count-change 1 3)) 0) 0)
; (+ (+ (+ (+ (count-change 11 1) (count-change 6 2)) (+ (count-change 1 2) (count-change -9 3))) 0) 0)
; (+ (+ (+ (+ (+ (count-change 11 0) (count-change 10 1)) (+ (count-change 6 1) (count-change 1 2))) (+ (+ (count-change 1 1) (count-change -4 2)) 0)) 0) 0)
; ...

; The algorithm is greedy type
; Order of growth for space is O(n)
; Order of growth for time. This recursion is hard to solve analytically. It seems like O(n^2) 🤷‍♂️