#lang sicp

; The sine of an angle (specified in radians) can be computed by making use of the approximation 
; sin x = x if x is sufficiently small, and the trigonometric identity

(define (сube x) (* x x x))

(define (p x) (- (* 3 x) (* 4 (сube x))))

(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))

; a. How many times is the procedure p applied when (sine 12.15) is evaluated?

; for x equals 4 // => (/ 12.15 (3^4)) that less then 0.1
; for x equals 5 // => (/ 12.15 (3^5)) that more then 0.1
; therefore p calls 5 times


; b. What is the order of growth in space and number of steps (as a function of a)
;    used by the process generated by the sine procedure when (sine a) is evaluated?

; time:
;   Angle is in every step reduced three times (n/3), after n iteration x decrease by 3^n.
;   Order of growth is logarithmic – O(log n)
;
; space:
;   Order of growth grows with the steps – O(log n)
